apiVersion: v1
kind: Service
metadata:
  name: database-app-service
spec:
  selector:
    app: database-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
